name: Call Reusable Workflow

on:
  push:
    branches: ['**']

  pull_request:
    branches: [main]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract Version from pubspec.yaml
        id: version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d+ -f1)
          echo "version=v$version"
          echo "version=v$version" >> $GITHUB_OUTPUT

  call-flutter-workflow:
    name: Calling Reusable CI Workflow
    needs: extract-version
    uses: Rite-Technologies-23/reusable-repo-flutter/.github/workflows/push.yml@main
    with:
      build_ios: ${{ vars.BUILD_IOS == 'true' }}
      flutter_version: ${{ vars.FLUTTER_VERSION }}
      flutter_channel: ${{ vars.FLUTTER_CHANNEL }}
      coverage_threshold: ${{ vars.COVERAGE_THRESHOLD }}

    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  call-release-workflow:
    name: Call Reusable Release Workflow
    needs: extract-version
    uses: Rite-Technologies-23/reusable-repo-flutter/.github/workflows/release.yml@main
    with:
      version: ${{ needs.extract-version.outputs.version }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

